"""Nova Coluna Tmanhos

Revision ID: 0adbd9d3e314
Revises: e7aeb670190a
Create Date: 2021-04-30 20:36:57.059667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0adbd9d3e314'
down_revision = 'e7aeb670190a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
