"""Nova Usuario

Revision ID: 783faaf3dbdc
Revises: 0adbd9d3e314
Create Date: 2021-04-30 20:49:41.426359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783faaf3dbdc'
down_revision = '0adbd9d3e314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
