"""Nova Usuario

Revision ID: d9681f2af1ba
Revises: 783faaf3dbdc
Create Date: 2021-05-01 11:18:26.820480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9681f2af1ba'
down_revision = '783faaf3dbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
